/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: harshidkannan (https://sketchfab.com/harshidkannan)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/apple-iphone-13-pro-max-1-free-3d89d78b91e546ed9610bc2bab9ddfc6
title: Apple Iphone 13 Pro Max (1) FREE
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Scene } from 'three'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/iphone.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, -0.01]} rotation={[-Math.PI / 2, 0, 0]}>
            <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
              <group scale={500}>
                <mesh geometry={nodes.Object_8.geometry} material={materials.Frame} />
                <mesh geometry={nodes.Object_10.geometry} material={materials.Frame2} />
                <mesh geometry={nodes.Object_12.geometry} material={materials.Port} />
                <mesh geometry={nodes.Object_14.geometry} material={materials.Antenna} />
                <mesh geometry={nodes.Object_16.geometry} material={materials.material} />
                <mesh geometry={nodes.Object_19.geometry} material={materials.material} />
                <mesh geometry={nodes.Object_21.geometry} material={materials.Bezel} />
                <mesh geometry={nodes.Object_23.geometry} material={materials.Body} />
                <mesh geometry={nodes.Object_25.geometry} material={materials.Wallpaper} />
                <mesh geometry={nodes.Object_27.geometry} material={materials.Camera_Glass} />
                <mesh geometry={nodes.Object_29.geometry} material={materials.Lens} />
                <mesh geometry={nodes.Object_31.geometry} material={materials.Material} />
                <mesh geometry={nodes.Object_34.geometry} material={materials.Body} />
                <mesh geometry={nodes.Object_36.geometry} material={materials.Glass} />
                <mesh geometry={nodes.Object_38.geometry} material={materials['Camera_Frame.001']} />
                <mesh geometry={nodes.Object_40.geometry} material={materials.material} />
                <mesh geometry={nodes.Object_43.geometry} material={materials.Screen_Glass} />
                <mesh geometry={nodes.Object_46.geometry} material={materials.Frame} />
                <mesh geometry={nodes.Object_49.geometry} material={materials.Frame} />
                <mesh geometry={nodes.Object_52.geometry} material={materials.Logo} />
                <mesh geometry={nodes.Object_55.geometry} material={materials.Body} />
                <mesh geometry={nodes.Object_57.geometry} material={materials.Gray_Glass} />
                <mesh geometry={nodes.Object_59.geometry} material={materials.Flash} />
                <mesh geometry={nodes.Object_61.geometry} material={materials.Port} />
                <mesh geometry={nodes.Object_63.geometry} material={materials.Camera_Frame} />
                <mesh geometry={nodes.Object_65.geometry} material={materials.Camera_Glass} />
                <mesh geometry={nodes.Object_67.geometry} material={materials.Lens} />
                <mesh geometry={nodes.Object_69.geometry} material={materials.Black_Glass} />
                <mesh geometry={nodes.Object_72.geometry} material={materials['Material.002']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/iphone.gltf')
